spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
  application:
    name: spring-alkmanistik-website
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  data:
    redis:
      host: localhost
      port: 6379
  security:
    user:
      name: Alk
      password: 12345

server:
  error:
    include-message: always
